name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
     inputs:
      challenge_id:
        description: 'Challenge id'
        required: true
        default: '1'
        type: string
      step:
        description: 'Step'
        required: true
        default: '1'
        type: string
        
env:
  CARGO_TERM_COLOR: always
  CHALLENGE_ID: ${{ inputs.challenge_id }} != '' & ${{ inputs.challenge_id }} `| '1'
  STEP: ${{ inputs.step }} != '' & ${{ inputs.step }} `| '1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Print inputs
      run: echo challenge_id => $CHALLENGE_ID , step => $STEP
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo run -- --file-path $(pwd)/inputs/challenge$(CHALLENGE_ID).txt --challenge-id $(CHALLENGE_ID) --step $(STEP)
